apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

managedNodeGroups:
  - name: ng-default
    instanceTypes:
      - t3.medium
      - t3a.medium
      - t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
