apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-eks
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
